"""empty message

Revision ID: b70ad0e9497d
Revises: 923e8e3f78cc
Create Date: 2020-05-01 10:39:18.917046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70ad0e9497d'
down_revision = '923e8e3f78cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description',
                                      sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column(
        'seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column(
        'website', sa.String(length=120), nullable=True))
    op.alter_column('Artist', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Artist', 'image_link',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=False)
    op.alter_column('Artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Artist', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.create_unique_constraint(None, 'Artist', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='unique')
    op.alter_column('Artist', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('Artist', 'image_link',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=True)
    op.alter_column('Artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Artist', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
