"""empty message

Revision ID: c6d18bd4a56f
Revises: b70ad0e9497d
Create Date: 2020-05-01 10:51:46.507823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d18bd4a56f'
down_revision = 'b70ad0e9497d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column(
        'genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description',
                                     sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column(
        'seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column(
        'website', sa.String(length=120), nullable=True))
    op.alter_column('Venue', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Venue', 'image_link',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=False)
    op.alter_column('Venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Venue', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('Venue', 'image_link',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=True)
    op.alter_column('Venue', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
